### ISSUE TITLE
About 'get_loss' method

### ISSUE THREAD

**Issue by ken-take-it-so-so** [DavidRuhe/simple-variational-diffusion-models#3]
Hello.  
I am taking notice of  "Variational Diffusion Models" and your blog(https://davidruhe.github.io/notes/Variational-Diffusion-Models).  
I have some questions.
https://github.com/DavidRuhe/simple-variational-diffusion-models/blob/a4ecc61a5c200341b4b0b7586fcfe65697750d9e/src/main.py#L504  
According to the paper, we can derive the distribution of $z_t$ given $x$ using formula(1).  I think this implementation is needed instead of `q_zt_zs` . What do you think about this ?  
https://github.com/DavidRuhe/simple-variational-diffusion-models/blob/a4ecc61a5c200341b4b0b7586fcfe65697750d9e/src/main.py#L508  
In diffusion loss, why gradient of $z_t$ is not computed ? In this case, is SNRNetwork not optimized ?  
I'm a beginner of deep learning programming.  
I would appreciate your cooperation.

**Comment by DavidRuhe** [comment]
Hi, thanks for your comment!

Formula 1 holds for any $z_t$ given $z_s$ so long as $t > s$. We put $z_0:=x$. 

When implementing the model I found that without detaching that gradient the optimization was highly unstable. SNRNetwork still gets gradients through `norm_nlogsnr_t`. 

In the meantime, an official implementation of the paper has been released. Perhaps you could cross-check with that implementation.

**Comment by DavidRuhe** [comment]
When $a_0=1$ and $\sigma_0=0$, the formulas are the same. Looking at the code, I see that for t=0 we get $\sigma^2_0 = \mathrm{sigmoid}(-10)=0.000045\approx 0$ and $\alpha^2_0=(1-0.000045)\approx1$ which is why I reused the function. One thing I realize now is that these bounds are currently learnable in the code, and so I'm not sure what will happen during training. Perhaps these should not be able to receive gradients. 

If you insist that these should be different, please leave a PR!

**Comment by ken-take-it-so-so** [comment]
@DavidRuhe, thank you for your thorough explanation! I understand.
